---
title: "Comparing CMIP5 and CMIP6 EEZ mean change across SSPs"
author: "Rich Cottrell"
date: "11/11/2022"
output: pdf_document
---

Set up
```{r setup, include=FALSE}

library(tidyverse)
library(here)
library(sf)
library(data.table)
library(dtplyr)
library(countrycode)
library(rnaturalearth)
library(rnaturalearthdata)
library(patchwork)



countries <- rnaturalearth::ne_countries(scale = "medium", type = "countries", returnclass = "sf")
bbox <- rnaturalearth::ne_download(scale = 50, type = "wgs84_bounding_box", category = "physical", returnclass = "sf")
eez_shp <- st_read(here("data/World_EEZ/eez_corrected.shp"))


```

Pull in EEZ data

```{r}
eez_data <- fread(here("data/EEZ_tcb.csv"))

eez_w_iso <- 
  eez_data |> 
  lazy_dt(immutable = FALSE) |> 
  mutate(iso3c = countrycode(sourcevar = EEZ, origin = "country.name", destination = "iso3c", warn = TRUE)) |> 
  mutate(iso3c = case_when(EEZ == "Comores" ~ "COM",
                           EEZ == "Micronesia" ~ "FSM",
                           TRUE~iso3c)) |> 
  filter(year %in% seq(from = 2090, to = 2099) & dataType == "per") |>
  group_by(iso3c, EEZ, ssp) |> 
  summarise(mean = mean(mean, na.rm = TRUE)) |> 
  as_tibble() |> 
    mutate(EEZ = gsub(pattern = "\\.", replacement = " ", EEZ)) |> 
  mutate(EEZ = if_else(EEZ=="Guinea Bissau", true = "Guinea-Bissau", false = EEZ))

#checking all eezs are the same for shapefile and data frame
eez_w_iso$iso3c |> unique() |> sort() == eez_shp$ISO_SOV1 |> unique() |> sort()

eez_w_iso$EEZ |> unique() |> sort() == eez_shp$SOVEREIGN1 |> unique() |> sort()

# Identify the country that does not match (Guinea-Bissau) and adjust it in code above 
# eez_shp$SOVEREIGN1 |> unique() |> sort() |> pluck(57)
# eez_w_iso$EEZ |> unique() |> sort() |> pluck(57)

```


Sort the EEZs to only include the country mainlands and not the territories
```{r}



#which countries have more than their eez i.e. territories

eez_miscellaneous <- eez_shp |> 
  group_split(SOVEREIGN1) |> 
  map_df(\(x){
    EEZ <- x$SOVEREIGN1 |> unique()
    nrows <- nrow(x)
    return(tibble(EEZ, nrows))
  }) |> 
 filter(nrows>1)


#create vector for acceptable EEZs to be included in the countries with external territories

mainland_EEZs <- c("Australian Exclusive Economic Zone", "Barbados Exclusive Economic Zone", "Brazilian Exclusive Economic Zone", "Canadian Exclusive Economic Zone", "Chilean Exclusive Economic Zone", "Chinese Exclusive Economic Zone", "Colombian Exclusive Economic Zone", "Costa Rican Exclusive Economic Zone", "Croatian Exclusive Economic Zone", "Danish Exclusive Economic Zone", "Dominican Republic Exclusive Economic Zone", "East Timorian Exclusive Economic Zone", "Ecuadorian Exclusive Economic Zone", "Eritrean Exclusive Economic Zone", "French Exclusive Economic Zone", "Guyanan Exclusive Economic Zone", "Haitian Exclusive Economic Zone", "Honduran Exclusive Economic Zone", "Icelandic Exclusive Economic Zone", "Indian Exclusive Economic Zone", "Jamaican Exclusive Economic Zone", "Japanese Exclusive Economic Zone", "Kenyan Exclusive Economic Zone", "Kiribati Exclusive Economic Zone (Phoenix Islands)", "Kiribati Exclusive Economic Zone (Line Islands)", "Kiribati Exclusive Economic Zone (Gilbert Islands)", "Madagascan Exclusive Economic Zone", "Mauritian Exclusive Economic Zone", "Dutch Exclusive Economic Zone", "New Zealand Exclusive Economic Zone", "Norwegian Exclusive Economic Zone", "Papua New Guinean Exclusive Economic Zone", "Peruvian Exclusive Economic Zone", "Portuguese Exclusive Economic Zone", "Qatari Exclusive Economic Zone", "Sao Tome and Principe Exclusive Economic Zone",  "Senegalese Exclusive Economic Zone", "South African Exclusive Economic Zone", "South Korean Exclusive Economic Zone", "Spanish Exclusive Economic Zone", "Sudanese Exclusive Economic Zone", "Taiwanese Exclusive Economic Zone", "United Arab Emirates Exclusive Economic Zone", "United Kingdom Exclusive Economic Zone",
"United States Exclusive Economic Zone", "Uruguayan Exclusive Economic Zone", "Venezuelan Exclusive Economic Zone")


#now filter EEZs to only include mainland EEZs

eez_shp_mainlands <- 
  eez_shp |> 
  group_split(SOVEREIGN1) |> 
  map_df(\(this_country){
    
    this_countryname <- this_country$SOVEREIGN1 |> unique()
    
    if(this_countryname %in% eez_miscellaneous$EEZ){
      
      this_country <- this_country |> filter(GEONAME %in% mainland_EEZs)
      
    }
    return(this_country)
    })



```

Mitigation map
```{r}

mitigation_ssp <- eez_w_iso$ssp |> unique() |> pluck(1)

eez_join_mitigation <- eez_shp_mainlands |> 
  left_join(eez_w_iso |> 
              filter(ssp== mitigation_ssp), 
            by = c("ISO_SOV1" = "iso3c")) |> 
  st_transform(crs = "ESRI:54030")


countries_robin <- countries |> st_transform(crs = "ESRI:54030")
bbox_robin <- bbox |> st_transform(crs = "ESRI:54030")


ggplot()+
  geom_sf(data = bbox_robin, fill="white", alpha =0.3, size=0.2)+
  geom_sf(data = countries_robin, fill = "grey95", size = 0.1, colour = "grey90")+
  geom_sf(data = eez_join_mitigation, aes(fill = mean), size = 0.2, colour = "grey70")+
  scale_fill_gradient2(low = "firebrick", high = "blue")+
  theme_bw()+
  theme(panel.border = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.text = element_text(size = 8),
        legend.title = element_text(size=8),
        plot.title = element_text(size=10, hjust =0.5))+
  labs(title = "Mitigation scenario", fill = "Mean biomass change (%)")+
  guides(fill = guide_colorbar(barwidth = 6, barheight=0.3, units = "cm", title.position = "top", title.hjust = 0.5))


ggsave(here("figures/mitigation_map.jpg"), dpi=600, width = 9, height=, units = "cm" )

```


High emissions SSP

```{r}

hi_emissions_ssp <- eez_w_iso$ssp |> unique() |> pluck(2)

eez_join_hi_emissions <- eez_shp_mainlands |> 
  left_join(eez_w_iso |> 
              filter(ssp== hi_emissions_ssp), 
            by = c("ISO_SOV1" = "iso3c")) |> 
  st_transform(crs = "ESRI:54030")

countries_robin <- countries |> st_transform(crs = "ESRI:54030")
bbox_robin <- bbox |> st_transform(crs = "ESRI:54030")


ggplot()+
  geom_sf(data = bbox_robin, fill="white", alpha =0.3, size=0.2)+
  geom_sf(data = countries_robin, fill = "grey95", size = 0.1, colour = "grey90")+
  geom_sf(data = eez_join_hi_emissions, aes(fill = mean), size = 0.2, colour = "grey70")+
  scale_fill_gradient2(low = "firebrick", high = "blue")+
  theme_bw()+
  theme(panel.border = element_blank(),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.text = element_text(size = 8),
        legend.title = element_text(size=8),
        plot.title = element_text(size=10, hjust =0.5))+
  labs(title = "High emissions scenario", fill = "Mean biomass change (%)")+
  guides(fill = guide_colorbar(barwidth= 6, barheight = 0.3, units = "cm", title.position = "top", title.hjust = 0.5))


ggsave(here("figures/high_emissions_map.jpg"), dpi=600, width = 9, height=8, units = "cm" )




```

```{r}

```

