---
title: "Plotting regional aggregations of mean and SD"
author: "Rich Cottrell"
date: "16/11/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(sf)
library(terra)
library(here)
library(rnaturalearth)
library(rnaturalearthdata)
library(patchwork)
library(ggnewscale)

```

Bring in shapefiles
```{r}

eez_shp <- st_read(here("data/raw_data/World_EEZ/eez_corrected.shp")) |> 
  select(GEONAME,geometry) |> 
  rename(region=GEONAME)
  
fao_area <- 
  st_read("/mnt/rdsi/raw_data/fao/FAO_AREAS_CWP/FAO_AREAS_CWP.shp") |> 
   select(F_AREA, geometry) |> 
   rename(region=F_AREA)

countries_shp <- ne_countries(scale="medium", returnclass = "sf") |> st_transform(crs = "ESRI:54030")


```


Plot CMIP5
```{r}

cmip5_mean <- readRDS(here("data/data_products/cmip5_mean_change_aggregated_by_region.rds"))
cmip5_sd <- readRDS(here("data/data_products/cmip5_SD_aggregated_by_region.rds"))



#MEAN CHANGE

#join mean data to joint eez and fao 

cmip5_mean_eez <- 
  eez_shp |>  
  left_join(cmip5_mean |> 
              mutate(region = gsub("High Seas, FAO area ", replacement = "", region)) , by = "region") |> 
  mutate(weighted_mean = case_when(weighted_mean < -50 ~ -50,
                                   weighted_mean > 50 ~ 50, 
                                   TRUE ~ weighted_mean)) |> 
  st_transform(crs = "ESRI:54030")


cmip5_mean_fao <- 
  fao_area |>  
  left_join(cmip5_mean |> 
              mutate(region = gsub("High Seas, FAO area ", replacement = "", region)) , by = "region") |> 
 mutate(weighted_mean = case_when(weighted_mean < -50 ~ -50,
                                   weighted_mean > 50 ~ 50, 
                                   TRUE ~ weighted_mean)) |> 
  st_transform(crs = "ESRI:54030")



cmip5_mean_p <- ggplot()+
   geom_sf(data = cmip5_mean_fao, aes(fill=weighted_mean), size=NA)+
  scale_fill_gradient2(low ="red", mid = "white", high = "blue", midpoint = 0, limits = c(-50,50), breaks = c(-50, 0, 50))+
  geom_sf(data = countries_shp, fill= "grey93", colour=NA, size=0.15)+
  theme_bw()+
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        plot.title = element_text(hjust = 0.5, size=10, vjust = -2),
        plot.title.position = "panel")+
  guides(fill="none")+
  new_scale_fill()+
  geom_sf(data = cmip5_mean_eez, aes(fill=weighted_mean), size=0.15)+
  scale_fill_gradient2(low ="red", mid = "white", high = "blue", midpoint = 0, limits = c(-50,50), breaks = c(-50, 0, 50))+
  labs(fill = "Biomass\nchange (%)\n ", title = "CMIP5")+
  guides(fill = guide_colorbar(barwidth = 0.5, barheight = 4.5, title.hjust = 0, title.position = "top"))+
  theme(legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 8),
        legend.text = element_text(size=8),
        legend.box.spacing = unit(-0.2, "cm"))
  
  

ggsave(plot = cmip5_mean_p, filename = here("figures/cmip5_mean_change.jpg"), device = "jpg", dpi = 600, width = 9, height = 6.5, units="cm")




#SD

cmip5_sd_eez <- 
  eez_shp |>  
  left_join(cmip5_sd |> 
              mutate(region = gsub("High Seas, FAO area ", replacement = "", region)) , by = "region") |> 
  st_transform(crs = "ESRI:54030")


cmip5_sd_fao <- 
  fao_area |>  
  left_join(cmip5_sd |> 
              mutate(region = gsub("High Seas, FAO area ", replacement = "", region)) , by = "region") |> 
  st_transform(crs = "ESRI:54030")



cmip5_sd_p <- ggplot()+
   geom_sf(data = cmip5_sd_fao, aes(fill=weighted_mean), size=NA)+
  scale_fill_gradient(low = "aliceblue", high = "dodgerblue4", limits = c(0,450))+
  geom_sf(data = countries_shp, fill= "grey93", colour=NA, size=0.15)+
  theme_bw()+
  theme(panel.grid = element_blank(),
        panel.border = element_blank())+
  guides(fill="none")+
  new_scale_fill()+
  geom_sf(data = cmip5_sd_eez, aes(fill=weighted_mean), size=0.15)+
  scale_fill_gradient(low = "aliceblue", high = "dodgerblue4", limits = c(0,450))+
  labs(fill = "Variability (SD)")+
  guides(fill = guide_colorbar(barwidth = 0.5, barheight = 4.5, title.hjust = 0, title.position = "top"))+
  theme(legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 8),
        legend.text = element_text(size=8),
        legend.box.spacing = unit(-0.2, "cm"))
  

ggsave(plot = cmip5_sd_p, filename = here("figures/cmip5_SD.jpg"), device = "jpg", dpi = 600, width = 9, height = 6, units="cm")





```

Plot CMIP6

```{r}


cmip6_mean <- readRDS(here("data/data_products/cmip6_mean_change_aggregated_by_region.rds"))
cmip6_sd <- readRDS(here("data/data_products/cmip6_SD_aggregated_by_region.rds"))



#MEAN CHANGE

#join mean data to joint eez and fao 

cmip6_mean_eez <- 
  eez_shp |>  
  left_join(cmip6_mean |> 
              mutate(region = gsub("High Seas, FAO area ", replacement = "", region)) , by = "region") |> 
  mutate(weighted_mean = case_when(weighted_mean < -50 ~ -50,
                                   weighted_mean > 50 ~ 50, 
                                   TRUE ~ weighted_mean)) |> 
  st_transform(crs = "ESRI:54030")




cmip6_mean_fao <- 
  fao_area |>  
  left_join(cmip6_mean |> 
              mutate(region = gsub("High Seas, FAO area ", replacement = "", region)) , by = "region") |> 
 mutate(weighted_mean = case_when(weighted_mean < -50 ~ -50,
                                   weighted_mean > 50 ~ 50, 
                                   TRUE ~ weighted_mean)) |> 
  st_transform(crs = "ESRI:54030")


cmip6_mean_p <- ggplot()+
   geom_sf(data = cmip6_mean_fao, aes(fill=weighted_mean), size=NA)+
  scale_fill_gradient2(low ="red", mid = "white", high = "blue", midpoint = 0, limits = c(-50,50), breaks = c(-50, 0, 50))+
  geom_sf(data = countries_shp, fill= "grey93", colour=NA, size=0.15)+
  theme_bw()+
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        plot.title = element_text(hjust = 0.5, size=10, vjust = -2),
        plot.title.position = "panel")+
  guides(fill="none")+
  new_scale_fill()+
  geom_sf(data = cmip6_mean_eez, aes(fill=weighted_mean), size=0.15)+
  scale_fill_gradient2(low ="red", mid = "white", high = "blue", midpoint = 0, limits = c(-50,50), breaks = c(-50, 0, 50))+
  labs(fill = "Biomass\nchange (%)\n ", title = "CMIP6")+
  guides(fill = guide_colorbar(barwidth = 0.5, barheight = 4.5, title.hjust = 0, title.position = "top"))+
  theme(legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 8),
        legend.text = element_text(size=8),
        legend.box.spacing = unit(-0.2, "cm"))
  
  

ggsave(plot = cmip6_mean_p, filename = here("figures/cmip6_mean_change.jpg"), device = "jpg", dpi = 600, width = 9, height = 6.5, units="cm")



#SD

#SD

cmip6_sd_eez <- 
  eez_shp |>  
  left_join(cmip6_sd |> 
              mutate(region = gsub("High Seas, FAO area ", replacement = "", region)) , by = "region") |> 
  st_transform(crs = "ESRI:54030")


cmip6_sd_fao <- 
  fao_area |>  
  left_join(cmip6_sd |> 
              mutate(region = gsub("High Seas, FAO area ", replacement = "", region)) , by = "region") |> 
  st_transform(crs = "ESRI:54030")



cmip6_sd_p <- ggplot()+
   geom_sf(data = cmip6_sd_fao, aes(fill=weighted_mean), size=NA)+
  scale_fill_gradient(low = "aliceblue", high = "dodgerblue4", limits = c(0,450))+
  geom_sf(data = countries_shp, fill= "grey93", colour=NA, size=0.15)+
  theme_bw()+
  theme(panel.grid = element_blank(),
        panel.border = element_blank())+
  guides(fill="none")+
  new_scale_fill()+
  geom_sf(data = cmip6_sd_eez, aes(fill=weighted_mean), size=0.15)+
  scale_fill_gradient(low = "aliceblue", high = "dodgerblue4", limits = c(0,450))+
  labs(fill = "Variability (SD)")+
  guides(fill = guide_colorbar(barwidth = 0.5, barheight = 4.5, title.hjust = 0, title.position = "top"))+
  theme(legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 8),
        legend.text = element_text(size=8),
        legend.box.spacing = unit(-0.2, "cm"))
  

ggsave(plot = cmip6_sd_p, filename = here("figures/cmip6_SD.jpg"), device = "jpg", dpi = 600, width = 9, height = 6, units="cm")




```


```{r}

((cmip5_mean_p|cmip6_mean_p)+
  plot_layout(guides = "collect")&
  theme(legend.position = "right"))/

(  (cmip5_sd_p|cmip6_sd_p)+
  plot_layout(guides = "collect")&
  theme(legend.position = "right",
        legend.box.spacing = unit(-0.5, "cm")))

ggsave(filename =  here("figures/cmip5_cmip6_mean_sd.jpg"), dpi = 600, width = 18, height =9, units="cm")


```

