library(tidyverse)
library(data.table)


#Base folder for project
base_folder <- "/rd/gem/private/users/camillan"

#Defining location of notebook outputs
out_folder <- file.path(base_folder, "FAO_Report")
if(!dir.exists(out_folder)){
  dir.create(out_folder)
}

country_level_folder <- file.path(out_folder, "country_level_gage")

fishmip_data <- read.csv(file.path(base_folder, "FAO_Report/table_stats.csv")) %>%
  mutate(pos_neg = ifelse(mean > 0, "positive", "negative")) %>% # ~200 regions, makes sense
  mutate(uncertain = ifelse(
    agreement < 80, "yes", "no"
  )) %>%
  filter(!is.na(mean)) %>%
  filter(spatial_scale=="countries")

country_continent <- fishmip_data %>% 
  distinct(figure_name, continent) # get distinct continent names with countries bc the admin file is missing continent names


####### get table of stats calculated for all spatial areas, including those aggregated by admiistrative country

# Countries (all EEZ grouped into country admin) only
fishmip_data_new <- read.csv(file.path(country_level_folder, "table_stats_country_admin.csv")) %>%
#cmip_data_new <- read.csv(here("data/table_stats_country_admin.csv")) %>%
  dplyr::rename(figure_name = Country_FAO) %>%
  left_join(country_continent) %>%
  mutate(continent = case_when(
    figure_name == "China" ~ "Asia", 
    figure_name == "India" ~ "Asia",
    figure_name == "Indonesia" ~ "Asia", 
    figure_name == "Peru" ~ "Americas", 
    figure_name == "Russian Federation" ~ "Europe",
    figure_name == "United States of America" ~ "Americas",
    figure_name == "Viet Nam" ~ "Asia",
    figure_name == "Kiribati" ~ "Oceania",
    TRUE ~ continent
  )) # fix missing continents in the admin country file


# format table for report


table_formatted<-fishmip_data_new %>% 
  mutate(id = paste(scenario, decade, sep = "_")) %>% 
  select(!c(scenario, decade, median, min, max, n_model)) %>% 
  mutate(mean = round(mean, 1), 
         sd = round(sd, 1),
         agreement = round(agreement),
         wilcox_p = ifelse(wilcox_p < 0.05, "*", NA)) %>% 
  pivot_wider(names_from = id, values_from = c(mean, sd, agreement, wilcox_p)) %>%
  select(!c(`wilcox_p_ssp126_2041-2050`,`wilcox_p_ssp126_2091-2100`)) %>% # wilcox and losses are the same across scenarios but different across decades so i keep only ssp585 for both decades. I also delete losses in 2041 as not considered in text.  
  relocate(spatial_scale, continent, figure_name,
           `mean_ssp126_2041-2050`,`sd_ssp126_2041-2050`,`agreement_ssp126_2041-2050`,
           `mean_ssp585_2041-2050`,`sd_ssp585_2041-2050`,`agreement_ssp585_2041-2050`,`wilcox_p_ssp585_2041-2050`,
           `mean_ssp126_2091-2100`,`sd_ssp126_2091-2100`,`agreement_ssp126_2091-2100`,
           `mean_ssp585_2091-2100`,`sd_ssp585_2091-2100`,`agreement_ssp585_2091-2100`,`wilcox_p_ssp585_2091-2100`) %>% 
  # mutate(continent = case_when(spatial_scale == "top_7_countries" & figure_name == "China" ~ "Asia",
  #                              spatial_scale == "top_7_countries" & figure_name == "India" ~ "Asia",
  #                              spatial_scale == "top_7_countries" & figure_name == "Indonesia" ~ "Asia",
  #                              spatial_scale == "top_7_countries" & figure_name == "Peru" ~ "Americas",
  #                              spatial_scale == "top_7_countries" & figure_name == "Russian Federation" ~ "Europe",
  #                              spatial_scale == "top_7_countries" & figure_name == "United States of America" ~ "Americas",
  #                              spatial_scale == "top_7_countries" & figure_name == "Viet Nam" ~ "Asia",
  #                              .default = as.character(continent))) %>% 
  # mutate(spatial_scale = factor(spatial_scale, levels = c("global", "top_7_countries", "countries", "FAO_area"))) %>% 
  arrange(spatial_scale, continent, figure_name) 

fwrite(table_formatted, here("data/table_stats_formatted_admin.csv"))


###### Full table with multiple spatial scales
# read in data generated by "global_biomass_circle_plots_and_map.Rmd"

fishmip_data_all<-readRDS("data/fishmip_summary_data.RDS")

table_formatted_full<-fishmip_data_all %>% 
  mutate(id = paste(scenario, decade, sep = "_")) %>% 
  select(!c(scenario, decade, median, min, max, n_model,pos_neg,uncertain)) %>% 
  mutate(mean = round(mean, 1), 
         sd = round(sd, 1),
         agreement = round(agreement),
         wilcox_p = ifelse(wilcox_p < 0.05, "*", NA)) %>% 
  pivot_wider(names_from = id, values_from = c(mean, sd, agreement, wilcox_p)) %>%
  select(!c(`wilcox_p_ssp126_2041-2050`,`wilcox_p_ssp126_2091-2100`)) %>% # wilcox and losses are the same across scenarios but different across decades so i keep only ssp585 for both decades. I also delete losses in 2041 as not considered in text.  
  relocate(spatial_scale, continent, figure_name,
           `mean_ssp126_2041-2050`,`sd_ssp126_2041-2050`,`agreement_ssp126_2041-2050`,
           `mean_ssp585_2041-2050`,`sd_ssp585_2041-2050`,`agreement_ssp585_2041-2050`,`wilcox_p_ssp585_2041-2050`,
           `mean_ssp126_2091-2100`,`sd_ssp126_2091-2100`,`agreement_ssp126_2091-2100`,
           `mean_ssp585_2091-2100`,`sd_ssp585_2091-2100`,`agreement_ssp585_2091-2100`,`wilcox_p_ssp585_2091-2100`) %>% 
  # mutate(continent = case_when(spatial_scale == "top_7_countries" & figure_name == "China" ~ "Asia",
  #                              spatial_scale == "top_7_countries" & figure_name == "India" ~ "Asia",
  #                              spatial_scale == "top_7_countries" & figure_name == "Indonesia" ~ "Asia",
  #                              spatial_scale == "top_7_countries" & figure_name == "Peru" ~ "Americas",
  #                              spatial_scale == "top_7_countries" & figure_name == "Russian Federation" ~ "Europe",
  #                              spatial_scale == "top_7_countries" & figure_name == "United States of America" ~ "Americas",
  #                              spatial_scale == "top_7_countries" & figure_name == "Viet Nam" ~ "Asia",
  #                              .default = as.character(continent))) %>% 
  # mutate(spatial_scale = factor(spatial_scale, levels = c("global", "top_7_countries", "countries", "FAO_area"))) %>% 
  arrange(spatial_scale, continent, figure_name) 

fwrite(table_formatted_full, here("data/table_stats_formatted_admin_full.csv"))




